name: Deploy STEMbrando Live

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@v5

      - name: Prepare STEMbrando Live
        run: |
          mkdir site
          curl -fsSL -H "Accept: application/vnd.github.raw+json" "https://api.github.com/repos/Anfaliz1703/stembrandoCI/git/blobs/902374fa4f4cf2c336bf7ae61d779e6528f5cc3b" -o site/index.html
          touch site/.nojekyll

      - uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - id: deployment
        uses: actions/deploy-pages@v4
